import Head from "next/head";
import { useSession } from "next-auth/react";
import dbConnect from "../utils/dbConnect";
import { useRouter } from "next/router";

export default function Home({ data }) {
  const posts = data.data;
  const { data: session } = useSession();
  if (session) {
    console.log(session);
  }
  const router = useRouter();

  function routePage(id) {
    router.push(`/posts/${id}`);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="welcome--container">
          {session ? (
            <div className="welcome">Welcome, {session.user.name}</div>
          ) : (
            <div className="welcome">Sign in to create posts </div>
          )}
        </div>
        <hr></hr>
        <div className="all">
          <div className="posts">
            {posts.map((each) => {
              return (
                <div className="post" key={each._id}>
                  <div className="post-container">
                    <p
                      onClick={() => routePage(each._id)}
                      className="post-title"
                    >
                      {each.title}
                    </p>
                    <img
                      onClick={() => routePage(each._id)}
                      className="post-img"
                      src={each.uploadedImage}
                    ></img>
                    <div className="profile-container">
                      <p className="user-name">{each.name}</p>
                      <img className="user-img" src={each.image}></img>
                    </div>
                    <hr className="post-break"></hr>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const data = await fetch("http://localhost:3000/api/auth/posts", {
    method: "GET",
  });
  const response = await data.json();
  return {
    props: {
      data: response,
    },
  };
};
